### ISSUE TITLE
Ability to capture the widget which is outside the viewport. 

### ISSUE THREAD

**Issue by Imgkl** [Imgkl/davinci#1]
If the widget is outside the viewport, meaning the entire widget comes into view only if we have to scroll, Then this package fails.

This can be achieved by converting the entire widget into a canvas and then export it as image.

#### Check if the widget is in viewport, i.e ` key.currentContext.findRenderObject ` is not null or doesn't throw any exception
  - If yes, use the existing method to export the widget into a image.
  - If not, convert the widget to canvas then export it as image.

**Comment by Imgkl** [comment]
Find the feasibility of going down the widget to canvas route or https://github.com/flutter/flutter/issues/40064

**Comment by xihuny** [comment]
How do I convert widget to canvas and then export it as image?

**Comment by saigkl** [comment]
By some research I've found these StackOverflow Answers, which might help in this scenario

**To convert widget to canvas**
https://stackoverflow.com/questions/61863958/how-can-i-paint-a-widget-on-a-canvas-in-flutter

**From Canvas to image.**
https://stackoverflow.com/questions/50320479/flutter-how-would-one-save-a-canvas-custompainter-to-an-image-file


I, personally haven't tested out these methods. Will update it when I do that.

**Comment by Imgkl** [comment]
@xihuny 
By some research, I've found these StackOverflow Answers, which might help in this scenario

To convert widget to the canvas
https://stackoverflow.com/questions/61863958/how-can-i-paint-a-widget-on-a-canvas-in-flutter

From Canvas to image.
https://stackoverflow.com/questions/50320479/flutter-how-would-one-save-a-canvas-custompainter-to-an-image-file

I, personally haven't tested out these methods. Will update it when I do that.

**Comment by Imgkl** [comment]
Implemented flutter/flutter#40064. Now you can make the widgets to images even if they are not mounted to the widget tree.

Thanks to <a href="https://github.com/christian-muertz">Christian Muertz</a>

update the package to `2.0.0`

**Comment by xihuny** [comment]
update which package?
