### ISSUE TITLE
Trying to install davinci throws this error. Seems like it's an issue with a dependent plugin.

### ISSUE THREAD

**Issue by waajito** [Imgkl/davinci#17]
![image](https://user-images.githubusercontent.com/34955537/120935744-d6693780-c721-11eb-97e9-17f64c25e030.png)

**Comment by Imgkl** [comment]
Hey @bharadwajpalakurthy,

I've been tracking this issue for some time. This is actually a dependency issue, `Gallery_saver`. 

Issue: https://github.com/CarnegieTechnologies/gallery_saver/issues/96.
PR: https://github.com/CarnegieTechnologies/gallery_saver/pull/122

I'll update the package once if the above-mentioned PR is merged.

**Comment by waajito** [comment]
Thanks for pointing out the PR. Greatly appreciated. Used the PR  to update the local cached gallery_saver file and that fixed it.
