### ISSUE TITLE
type 'RenderConstrainedBox' is not a subtype of type 'RenderRepaintBoundary' in type cast

### ISSUE THREAD

**Issue by mingV2019** [Imgkl/davinci#19]
Uint8List? thumbData = await DavinciCapture.click(globalKey, fileName: "Hello", openFilePreview: false, returnImageUint8List: true);

result:
I/flutter (27697): type 'RenderConstrainedBox' is not a subtype of type 'RenderRepaintBoundary' in type cast

**Comment by Imgkl** [comment]
Hey @mingV2019,

I'll test this and Fix it soon. Thanks for bring this to my notice.

**Comment by Imgkl** [comment]
Closing this since I'm not able to recreate it on my end. Please feel free open this issue. along with an issue description, some stack trace, and a reproducible code would be great to debug.
