### ISSUE TITLE
Support Dart 3 [ANALYSIS ISSUE]

### ISSUE THREAD

**Issue by tusharbhambere** [Imgkl/davinci#29]
Error: No named parameter with the name 'window'.
        window: ui.window,
        ^^^^^^
Flutter Version 3.10.0 Dart version  3.0.0
Breaking Changes: Window singleton is deprecated in preparation for multi-window support. Android Studio's Flamingo upgrade might cause some errors due to Java SDK and Gradle version mismatch.

**Comment by Imgkl** [comment]
This issue is now fixed in the version 2.1.0
