### ISSUE TITLE
Just save generated images

### ISSUE THREAD

**Issue by lucas-gauer** [Imgkl/davinci#8]
It is only possible to choose between return uint8 list and open preview.
There is no way to just save the file.

I know that having the uint8list i can save the file. But i think it would be nice if the package did it.
The share package accepts a path for sharing files. I want to just share the image without previewing it.

**Comment by Imgkl** [comment]
Hey @lucas-gauer,

I agree, having an option to save the generated file directly to photos is definitely a good enhancement. I'll try to add it soon. 

Thanks so much for your suggestion. 👍🏻

**Comment by Imgkl** [comment]
@lucas-gauer,
Version 2.0.1 is out. 
Now you can save the images directly to the gallery/photos app. Check the readme for more info.
````
await DavinciCapture.click(imageKey, fileName: "Hello", saveToDevice = true, album: "Davinci", openFilePreview = false);
````
